### ISSUE TITLE
Create Datapad Templates

### ISSUE THREAD

**Issue by bheiskell** [wrycu/StarWarsFFG-Enhancements#1]
I have two datapad templates. One for general information and one for bounties. I'll find a way to standardize these for inclusion in a module.

**Comment by bheiskell** [comment]
@wrycu We need to provide a way to template a Journal. We should replace the "Create new opening crawl" scene controls button with this workflow.

Options
1. Add a button to the Journal's side bar under "Create Entry" and "Create Folder" titled "Create Template".
2. Same as above, except "Create from FFG Template"
3. Hook the "Create Entry" button/application. Add a drop down for the template type, with "Blank" being the default.
4. Provide compendium with the Journal templates in it.

Option 3 is less invasive, but also less discoverable and probably more brittle. Option 4 is probably the least discoverable. It also couldn't be localized, I don't think.

What would you prefer?

**Comment by wrycu** [comment]
I'm in favor of 1, though with a perhaps less confusing name like `Create from Datapad template` or something. We may want to change our minds based on actually using it, though.

**Comment by bheiskell** [comment]
I will replace the create new opening crawl with create from datapad template.

**Comment by bheiskell** [comment]
Implemented.
