### ISSUE TITLE
[Bug] Item Animation Failure

### ISSUE THREAD

**Issue by tim-bersau** [wrycu/StarWarsFFG-Enhancements#100]
**Foundry Version:** Version 9 Build 245 (9.245)
**Star Wars FFG System Version:** 1.72
**FFG Enhancements Module Version:** 0.2.7

Item-based animations are failing to trigger.

If you use the default Star Wars _skill_ animations, those work fine. If you use the default Star Wars _grenade item_ animation, that fails. If you attempt to make a custom item animation, that fails.

In this clip I demonstrate the problem. I show that the animations are enabled, then I show that I have two items; an "Axe" with a custom animation & sound, and a "Grenade", with unedited default values. Neither of those work, but when I then do a Ranged-Heavy skill roll, the default laser animation for that works fine.

https://user-images.githubusercontent.com/10822280/152024067-ceb8db9b-d1d6-40f4-b9a2-32ccc71128d8.mp4

**Comment by wrycu** [comment]
I can't reproduce with an actor with both a grenade and non-grenade item - both animations play normally using default values. Can you please open the dev console (f12 in browsers) and include a screenshot of any errors?

Additionally, I see you're using the native Foundry UI here. Does anything happen differently if you use a real browser?

Lastly, please disable all modules but mine and confirm that the issue still occurs.

**Comment by tim-bersau** [comment]
> I can't reproduce with an actor with both a grenade and non-grenade item - both animations play normally using default values. Can you please open the dev console (f12 in browsers) and include a screenshot of any errors?
> 
> Additionally, I see you're using the native Foundry UI here. Does anything happen differently if you use a real browser?
> 
> Lastly, please disable all modules but mine and confirm that the issue still occurs.

Did so. In the following clip I run Foundry through Chrome and disabled all modules except for FFG Enhancements (& its dependencies). Animations still not triggering.

https://user-images.githubusercontent.com/10822280/152204146-9f6d9c70-4c1d-4e28-8cf3-2c15e97196c6.mp4

I'm not experience with parsing issues in browser consoles, but this was the only thing that looked like a message that popped up:

![screencap](https://user-images.githubusercontent.com/10822280/152204335-0b531e7c-7c09-4060-90b5-25955e5a8c94.png)

**Comment by wrycu** [comment]
Thanks, the log shows no errors (meaning the code ran properly). Can you attach the sound and animation files you're trying?

**Comment by tim-bersau** [comment]
> Thanks, the log shows no errors (meaning the code ran properly). Can you attach the sound and animation files you're trying?

Ones that already existed in the JJB2A pack & the FFG enhancement sounds. (Basically tried to recreate a working default animation to rule out custom content).

Going to attempt a complete Foundry wipe and reinstall everything.

**Comment by tim-bersau** [comment]
> > Thanks, the log shows no errors (meaning the code ran properly). Can you attach the sound and animation files you're trying?
> 
> Ones that already existed in the JJB2A pack & the FFG enhancement sounds. (Basically tried to recreate a working default animation to rule out custom content).
> 
> Going to attempt a complete Foundry wipe and reinstall everything.

Complete fresh install & data folder wipe fixed it. I wish I knew why. (Before this complete reinstall) Foundry asked me to reinstall the client when upgrading from 8.8 to 9.0, maybe something was screwy when the client was reinstalled & my data folder was just updated normally.
