### ISSUE TITLE
[Feature] Automated Animation or More Customizable and improvement of FFG Star Wars Enhancement

### ISSUE THREAD

**Issue by Thorshko** [wrycu/StarWarsFFG-Enhancements#101]
Hi :) . I really like the module FFG Star Wars Enhancement but, it seems to bad that i can't customize the effects and sounds for each weapon. For example, there is a sound for light weapons, lightsabers, heavy weapons, brawl, etc... But an artillery weapon like rocket launcher doing "pew pew pew" like a Tie Fighter is not... really immersive. The existing things are really good but something is missing, and sometimes the distance reduce the original size of the animation (less thick/large than expect, less long). Could it be possible, please, to have the means to do it ? I'm aware that the module Automated Animation didn't work with Star Wars FFG but it could be really nice to have some effects and sounds full customizable for better immersion. As far as i could see, you use JB2A Animation for animation. Thanks by advance. Your work is really amazing.

**Comment by wrycu** [comment]
You can customize on a per-actor basis.  To do this, click the Enhancements image on a scene and then click the attack icon.

![image](https://user-images.githubusercontent.com/4709746/152199349-4245ca9b-3b2a-409e-a775-ab37f33f46a5.png)

![image](https://user-images.githubusercontent.com/4709746/152199368-298356d7-dbf0-40be-ab3d-d5c3356865ae.png)

This opens up a menu with actors and their items, allowing you to overwrite the default values on a per-actor / item basis.

![image](https://user-images.githubusercontent.com/4709746/152199455-c1233a63-2400-414f-b678-06a17f0524bf.png)

**Comment by Thorshko** [comment]
Oh ok my thanks ^^. It could be pretty good if you'll do a feature with Otigon from Animated Animation, his work gain us a lot of time with a super friendly UI to automatize these sounds and animation. But i can understand if you don't want it. Thanks for your work it is already amazing :)

**Comment by wrycu** [comment]
I've personally found that most of it works quite well by default.  Looking at that module, it appears to map item / spell names to animations. Sadly, we don't have a star wars library of animations / sounds, so this isn't really possible for our use case. 

Thanks for the feedback, though! Please feel free to open a new issue if you have other thoughts.

**Comment by Thorshko** [comment]
Okay i understand it ^^. There is a lot of animation already existing to fit some Star Wars effects. I don't ask the perfect one but something close to it :). Other thing, it could be good if you allow us to create new categories of weapon with type of animation in it, because it took pretty much time to set each customizable animation and sound for each object or actor when a type of weapon doesn't fit in the preset. I totally understand if you sent me away because you don't have the time for this ^^. Being able for us to create new categories will gain us a lot of time. And also if you have a Patreon i would like to support your work because even if it needs a little bit of improvments (no offense), your work is super amazing.
