### ISSUE TITLE
[Request] Animation Improvements

### ISSUE THREAD

**Issue by tim-bersau** [wrycu/StarWarsFFG-Enhancements#103]
The current animation system is;

**Melee Items:** One animation hit.
**Ranged Items:** Random number of animation hits.

While I love the default 'random number of animation hits' for ranged items, it'd be beneficial if we had more control over the behavior.

This could be accomplished by letting us choose if the animation triggers "once" or a "random amount of times". Perhaps even a numerical entry field like "2" or "4" times?

Having this control would open up options for ranged items to be locked down to "once" when it makes narrative sense, as well as allowing melee items to be shown off in a flurry of blows. (However, ranged animation effects usually look better when looped multiple times- melee animations may not look as well given the same option.) In any case this would still be a win for ranged effects.

**Comment by wrycu** [comment]
Done, will be released in `0.2.8`. Thanks for the suggestion!
