### ISSUE TITLE
Animations don't work

### ISSUE THREAD

**Issue by juanru87** [wrycu/StarWarsFFG-Enhancements#106]
Hi, after upgrading Foundry to version 9 the module's attack animations have stopped working. I have deleted the module and reinstalled it but the problem continues. Is there any solution? Thanks.

**Comment by wrycu** [comment]
The module supports Foundry v9. Please include your Foundry, System, and module versions, along with any errors (from the dev console).

**Comment by juanru87** [comment]
I already managed to solve it. I only had to enter a number in "#animation count" and it works. Thank you very much.
