### ISSUE TITLE
Unable to import character XML from Oggdude CharGen versions 2.3.1, 2.3.2, 2.3.3, 2.3.4

### ISSUE THREAD

**Issue by theonlytimbo** [wrycu/StarWarsFFG-Enhancements#107]
The export character XML files from Oggdude's Character Generator version 2.3.1 and later are unable to be imported into StarWarsFFG Enhancements. This is for exported Player Characters. NPCs still seem to import successfully through all versions.

**Comment by wrycu** [comment]
The enhancements module doesn't do importing - the [system](https://github.com/StarWarsFoundryVTT/StarWarsFFG) does. You should open an issue there, and it'd be more helpful for the devs if you included a screenshot of the error (you can open the dev console with f12) and/or an example file you're using.
