### ISSUE TITLE
Module.json points to old version of FXMaster

### ISSUE THREAD

**Issue by boostedPeaks** [wrycu/StarWarsFFG-Enhancements#111]
If you don't have FXMaster installed when you install this module, the prompt to install it as a dependency points to an old (version 1.2.1) version of FXMaster. Therefore, unless you update it to the latest (2.4.0 I believe), the module is broken and scenes will not load.

it is pointing to a version on gitlab that hasn't been updated in 9 months, rather than the up-to-date one here:
https://github.com/ghost-fvtt/fxmaster

**Comment by wrycu** [comment]
```
ghost — Today at 12:28 PM
Yeah, that’s from before I have taken over the module. Use this manifest URL instead: https://github.com/ghost-fvtt/fxmaster/releases/latest/download/module.json 
```

**Comment by wrycu** [comment]
> ghost — Today at 12:29 PM
> Also, i don’t think you even need to specify the manifest at all for dependencies. If you don’t, foundry will simply pick the latest version that’s listed

**Comment by wrycu** [comment]
Can confirm, it grabbed a much newer version without the manifest specified. I'll remove it.

**Comment by wrycu** [comment]
Done; prepped for release in `0.2.9`.
