### ISSUE TITLE
dice_helper not working with translations

### ISSUE THREAD

**Issue by ercete** [wrycu/StarWarsFFG-Enhancements#115]
As my FoundryVTT is configure and translated in french, dice_helper is not working.
As a workaround, I simply translated the file dice_helper.json in french but the core problem is : working names of skills should not be translated.
But as SWFFG-Enhancements is guessing the skill from the flavor text, it's hard to blame it.

[dice_helper.json.zip](https://github.com/wrycu/StarWarsFFG-Enhancements/files/8599119/dice_helper.json.zip)

**Comment by wrycu** [comment]
Sadly, it's an issue I couldn't work around while providing a JSON method of storing/accessing the talents. I'll update the wiki page with your translation - thanks!

**Comment by ercete** [comment]
This issue can now be set as fixed.
