### ISSUE TITLE
Dice Helper not working for Ranged attacks

### ISSUE THREAD

**Issue by ravenmaster001** [wrycu/StarWarsFFG-Enhancements#120]
I've noticed that the dice helper doesn't actually function for any of the ranged attacks, after some poking around with the debugger it seems this is exclusively because these skills have spaces and we end up comparing nbsp from the output of the load_data function with a normal space from the messagedata.

![image](https://user-images.githubusercontent.com/5484891/182313628-ca051deb-834d-4a19-9864-c8a651c97249.png)
![image](https://user-images.githubusercontent.com/5484891/182315765-410c334d-88df-4554-b7e0-6d501fb5d877.png)

Occurs in both:
Firefox 103.0 (64-bit)
Chrome 103.0.5060.134 (64-bit)

**Comment by ravenmaster001** [comment]
Work around rename in the dice_helper journal entry:
"SWFFG.SkillsNameRangedHeavy" -> "ranged: heavy"
"SWFFG.SkillsNameRangedLight" -> "ranged: light"

**Comment by wrycu** [comment]
Interesting. I'll do some more testing. In previous versions, we ran into the opposite issue - we compared a normal space to nbsp. 

@ravenmaster001 what version of Foundry, Star Wars, and the module are you using? Are you using Forge?

**Comment by ravenmaster001** [comment]
I'm hosting the service on an Ubuntu server; 18.04.5 LTS (GNU/Linux 5.4.0-1086-azure x86_64)

Otherwise the versions of other bits and pieces are:
Foundry 9 build 269
Star Wars FFG  1.72
FFG Star Wars Enhancements 1.0.0

**Comment by Cryotechnik** [comment]
Hey, I'm having the same issue. Do you know if this problem has a fix?

**Comment by wrycu** [comment]
@Cryotechnik @ravenmaster001 what language are you using?

**Comment by Cryotechnik** [comment]
@wrycu English, or do you mean coding language?

**Comment by wrycu** [comment]
Nope, that's what I was looking for, thanks. What foundry version and did you start the world in that version or was it migrated from an earlier version?

**Comment by Cryotechnik** [comment]
Fresh world as of yesterday with the latest version (V10 Build 291). I'm using foundry through The Forge if that's helpful.

**Comment by wrycu** [comment]
Just tested this with the latest everything on a brand new world and it worked properly.

**Comment by Cryotechnik** [comment]
I am still experiencing it, even in a new world. Do you have any ideas for me to try? This world only has the system and the enhancement module installed.
![Screenshot (1)](https://user-images.githubusercontent.com/123840026/216473764-c54d7518-7e84-4ad7-94b4-c74a3aaf88c3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/123840026/216473787-8c9b78d1-b3b8-43b5-9eb2-d4790cc13053.png)

**Comment by Cryotechnik** [comment]
@ravenmaster001 Is this producible for you?

**Comment by wrycu** [comment]
Fixed, will be released in `2.0.1`.
