### ISSUE TITLE
Attack animation

### ISSUE THREAD

**Issue by Ryan-BLKST** [wrycu/StarWarsFFG-Enhancements#124]
Hello,

It seems that bringing up the attack animation menu (in FFG Enhancement) triggers 250 warnings in the console, I am unable to change the sound, it does not save.  
  
Tested on v1.80-alpha7

**Comment by wrycu** [comment]
confirmed. I totally skipped over that when I was testing. I'll get a fix out in the next few days

**Comment by wrycu** [comment]
Fixed, will be released in the stable release for v10. Thanks for the report!
