### ISSUE TITLE
Request: System agnostic opening crawl

### ISSUE THREAD

**Issue by SmartASCII** [wrycu/StarWarsFFG-Enhancements#126]
I messed with FFG for a while, including these enhancements, and really loved how the opening crawl here looks.

Would it be possible to extract this opening crawl into a system agnostic module for use in other systems? Currently using [Space Wars Text Crawl](https://github.com/jsavko/swtextcrawl) and I'd love to use this one instead.

**Comment by wrycu** [comment]
The underlying system is undergoing a complete rewrite by the core author, with a desire to modularize most of the functionality currently present in it. Once that happens, this module will need to be rewritten. I think that would be a good time to consider releasing the crawl as a dedicated module.

@bheiskell FYI in case you want to help this poor soul extract the relevant code for their own use before the system rewrite is done.

**Comment by SmartASCII** [comment]
Sounds great! I was able to make modifications locally to remove ffg system hooks and requirements to make the crawl and hyperspace transition work for OD6S for now, but will definitely keep an eye out for any official releases!

**Comment by DeanMaxwell** [comment]
> Sounds great! I was able to make modifications locally to remove ffg system hooks and requirements to make the crawl and hyperspace transition work for OD6S for now, but will definitely keep an eye out for any official releases!

Can you explain how you managed to accomplish this?
