### ISSUE TITLE
Attack animation

### ISSUE THREAD

**Issue by Ryan-BLKST** [wrycu/StarWarsFFG-Enhancements#129]
Hello,

It seems that localized 'global value' name is messing up the per item attack animation.
On the french version, the popup brings (valeur global) as default but it cannot be saved as such, the system displays 'Custom animation was removed'.
It 'works'  when (global value) is placed instead but I cannot play custom sounds.

Tested on blank world, 1.80-alpha8 / FFG Star wars Enhancements 2.0.0
![Uploading Capture.PNG…]()

Thank you again for your work !

**Comment by wrycu** [comment]
I think you're misunderstanding how it works. You cannot set a custom value for one part; you must set a custom value for each of the three fields - animation file, sound file, and number of times to play. If you leave any of them as default, it will unset it instead.

**Comment by Ryan-BLKST** [comment]
Isn't the (global value) supposed to get the value from the global FFG Enhancement setting ?

Also, when trying to set with default values (copy pasted from the settings), it does not work
![Capture](https://user-images.githubusercontent.com/115180991/216567511-aed5ea3a-bdf4-4796-a30f-76dd4af30441.PNG)

**Comment by wrycu** [comment]
`(global value)` (or the localized version) is supposed to use the values set in the module settings. You can only set custom values in that window when none of them are set to `(global value)`.

What happens when you try to save with your screenshot?

**Comment by Ryan-BLKST** [comment]
> You can only set custom values in that window when none of them are set to (global value).  
  
I do not understand, do you mean the global settings (in Options => FFG Enhanced => Attack animations) must be blank for the custom values to work ?

> What happens when you try to save with your screenshot?  

It saves but no sounds or animation is played when attacking

**Comment by wrycu** [comment]
This will not work:

![image](https://user-images.githubusercontent.com/4709746/216669641-e59c1788-5a03-40de-92ba-67bf1d084195.png)

Neither will this:

![image](https://user-images.githubusercontent.com/4709746/216669706-e1e70322-b5b7-4f0a-a985-641a57e0e47c.png)

_All settings must be set to something other than the default value or it will "remove custom animation"._

---

Can you try changing the skill the weapon is using and let me know if it works for any skill?

**Comment by Ryan-BLKST** [comment]
The error may actually be somewhere else.  
I was testing with 1 animation count, it does not work. But when testing with values of 2 or more, it works.

It seems sound and animation are played 1 time less than the value indicated in "Animation count".

**Comment by wrycu** [comment]
Thanks for offering to take this @bheiskell, looking forward to your fix

**Comment by bheiskell** [comment]
Chatting with @wrycu, there may be an off by one bug, causing 1 to become 0 attacks.

**Comment by bheiskell** [comment]
I confirmed it's an off by one in my local environment. Looking into how to fix it. (As a work around, set animation count = 2).

**Comment by wrycu** [comment]
Will be released in `2.0.2`.
