### ISSUE TITLE
Automatically renames actors in combat (to generic "PC" and "NPC" slots)

### ISSUE THREAD

**Issue by Tejasranger** [wrycu/StarWarsFFG-Enhancements#130]
Is there any way to turn off this feature, or is there a way to save the character names and art so that when I add them to the combat tracker it does not lose their art and name?

**Comment by wrycu** [comment]
Yes, it is "auto-rename combat actors" in the settings.

![image](https://user-images.githubusercontent.com/4709746/216493475-4c88622c-1ca8-4337-94c6-16ccf998c7c9.png)

**Comment by Tejasranger** [comment]
thank you!
