### ISSUE TITLE
Tests sometimes fail when run interactively without focus

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#158]
Typing into elements sometimes fails when tests are run interactively without leaving the window in focus for the entire time.

**Comment by wrycu** [comment]
It reports true in both cases.

**Comment by bheiskell** [comment]
Confirmed that we're running the same version of Cypress.

**Comment by bheiskell** [comment]
Seems to be an issue with Cypress upstream: https://github.com/cypress-io/cypress/issues/21673

There might be a flag to send, uncertain. In the meantime, we can manually toggle the dev tools to pretend to be in focus.
