### ISSUE TITLE
Investigate actively-selected combat slots

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#16]
Allow players and the GM to "grab" a slot in combat to show who is taking their turn.

* This should rename the slot once it's grabbed
* It can apply a status effect to tokens after they end their turn
* Boost / setback macro can be configured to note who gave the die if this is enabled

**Comment by wrycu** [comment]
I'm going to push for this to be included in the new system rather than try to implement it myself.

**Comment by Sonny-Crockett** [comment]
Sounds great!
