### ISSUE TITLE
Minion groups not getting minion icon applied

### ISSUE THREAD

**Issue by locke4242** [wrycu/StarWarsFFG-Enhancements#164]
In v10 the minion tokens are not getting the minion icon applied unless you link the actor data to the token. If you do link the actor data to the token, then once you increase the quantity of the units to two or higher then the icon shows up. If you unlink the actor data the minion icon never appears no matter what the quantity is set to.

Leaving the actor data unlinked, if you set the quantity on the actor two or more before dragging their token onto the canvas it DOES add the minion icon with the quantity set correct. After the token is on the canvas though, increases or decreases to the minion quantity do not change the number on the associated minion icon. 

Note, the Adversary icon is being set properly when the token has the Adversary talent so this part of the module IS working to some degree.

**Comment by sanpats** [comment]
I have this issue too.

**Comment by ercete** [comment]
I recently upgraded to v10 and encountered this issue.
@wrycu : you can assigned it to me.

**Comment by wrycu** [comment]
understood, thanks for the help :)

**Comment by wrycu** [comment]
@ercete not that there's the slightest rush, but are you working on this?

**Comment by ercete** [comment]
Sorry, still didn't found the time to dive into it.

**Comment by g1eagle** [comment]
In V11 switching to Condition Lab & Triggler fixed the minions icon not showing up in my game. In V10 CUB still worked fine for me. So if you upgrade to V11 I would recommend switching from CUB (It's broken anyway) to Condition Lab & Triggler.

**Comment by locke4242** [comment]
> In V11 switching to Condition Lab & Triggler fixed the minions icon not showing up in my game. In V10 CUB still worked fine for me. So if you upgrade to V11 I would recommend switching from CUB (It's broken anyway) to Condition Lab & Triggler.

No luck for me. Updated to V11 and switched to Condition Lab and Triggler and everything except the minion icons is working still.

**Comment by wrycu** [comment]
Fixed, will be released in `2.0.5`. Thanks for the report!

**Comment by ercete** [comment]
Yet another promise I didn't fullfill, sorry @wrycu and thank you for the fix !

**Comment by wrycu** [comment]
It's fine, thanks for taking a look.
