### ISSUE TITLE
Saga Edition compatability? / Make parts of module system independent?

### ISSUE THREAD

**Issue by themaster567** [wrycu/StarWarsFFG-Enhancements#169]
I play Saga Edition and there are functions of the mod like the intro creator, transitions, and the bounties + datapad entries that I think could be made system independent without much difficulty. In addition, the shop generator, the attack animations, the renamer, and the status adder could probably be re-targeted for Saga equivalents without being too crazy.

**Comment by wrycu** [comment]
Feel free to rip code out and port it to another module. This one is designed specifically for the FFG system, though - sorry, I simply don't have the time to rewrite it to be generic.
