### ISSUE TITLE
Problem with combat tracker after system update

### ISSUE THREAD

**Issue by robert16444** [wrycu/StarWarsFFG-Enhancements#181]
After system update, when the combat encouter is started the initiative slots are not automatically claimed, and after "taking out" the tab with the combat tracker, it takes up the entire length of the screen (like on a screen shot).

![obraz_2024-03-04_195820257](https://github.com/wrycu/StarWarsFFG-Enhancements/assets/40506857/1f471aaf-fafb-4337-8c8c-b8c26a175c3f)

**Comment by wrycu** [comment]
I'm not sure what bug your describing. You seem to be describing system functionality, but you've filed the issue for a module. Can you reword and/or expand on what the issue is?

**Comment by robert16444** [comment]
Sorry, my bad - I got the wrong repositories. It should be system one.
