### ISSUE TITLE
Blaster .webm animation not aligned

### ISSUE THREAD

**Issue by Ryan-BLKST** [wrycu/StarWarsFFG-Enhancements#182]
Hello !
When using the attack animation, the .webm animation is not placed correctly. 
It is on the right axis but the starting point and the end point are not properly placed.

**Comment by wrycu** [comment]
@Ryan-BLKST do you have a recording of this? Along with any info about where you're hosting the game, versions, and your browser. I cannot reproduce.

**Comment by Ryan-BLKST** [comment]
Here is a video of the animations : https://youtu.be/18y_areNE2g  
  
World is blank, foundry v11 and the system is v1.808.
Only the 6 mandatory modules.

**Comment by Ryan-BLKST** [comment]
It seems that switching the system to english disables the bug, I swithced when attempting to capture the bug.
It is consistent on the french version. 

https://youtu.be/sd2YLSg2PVo

**Comment by wrycu** [comment]
Done, will be released in `2.1.0`. Thanks for the report and video.
