### ISSUE TITLE
Player character sheets not opening

### ISSUE THREAD

**Issue by Meenbe** [wrycu/StarWarsFFG-Enhancements#185]
StarWarsFFG-Enhancements seems to be blocking me as GM from opening player character sheets. Permissions are set to observer for all and owner for the relevant player. Getting the below error and find the culprit seems to be indicating this module:

![image](https://github.com/wrycu/StarWarsFFG-Enhancements/assets/167745239/efd5f384-f9b0-4a0f-bd98-f98b824ab270)

**Comment by wrycu** [comment]
You have set the default sheet to be vendor, instead of a specific sheet. Changing this (likely in the vendor you were editing previously) will correct the issue.

**Comment by Meenbe** [comment]
> You have set the default sheet to be vendor, instead of a specific sheet. Changing this (likely in the vendor you were editing previously) will correct the issue.

Amazing thanks - exactly what it was.
