### ISSUE TITLE
Dice_helper: Does not work ifthe setting name is changed

### ISSUE THREAD

**Issue by TeddyBears** [wrycu/StarWarsFFG-Enhancements#188]
If I change the name of the dice_helper journal in settings, the feature doesnot work anymore.
The page into the journal use the journal name when it is created. But the test to take the content of the page is using "dice_helper". so the test return false and the ui message is displayed.

https://github.com/wrycu/StarWarsFFG-Enhancements/blob/893cfa58d6c538858ab1c2658cb06014d864c095/scripts/dice_helper.js#L274

**Comment by wrycu** [comment]
I can't reproduce this. It's possible I fixed it in my working code.

While it is checking for a _page_ named `dice_helper`, the page is created with that regardless of the setting, as the setting impacts the journal name only.
