### ISSUE TITLE
Dice Helper throws an error

### ISSUE THREAD

**Issue by AvDalfsen** [wrycu/StarWarsFFG-Enhancements#201]
Foundry version: 11.315 (haven't updated yet because a key module is still lacking V12 support)
Module version: 2.1.0

I initially had an edited Dice_helper.json, so as to include more skills, but I replaced that with the original one and the error persists.

![image](https://github.com/wrycu/StarWarsFFG-Enhancements/assets/42408840/f76948e5-eaf6-4629-8ca0-02fa52feeddd)

![image](https://github.com/wrycu/StarWarsFFG-Enhancements/assets/42408840/c9be84f3-1427-4c76-a44e-34afc083b82c)

**Comment by wrycu** [comment]
This version is not compatible with Foundry v11. Please install an older version or update Foundry.
