### ISSUE TITLE
Improve intro crawl

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#24]
- [x] Add delay playback setting - our audio file delays a bit, but others may not, resulting in a dsync'ed experience
- [x] Consider not having the image aligned right, or at least providing an option for it
- [x] Consider having a font size / zoom option
- [ ] Look into an improved experience for short intros
- [x] Improve text coverage of available space

**Comment by basicgm** [comment]
Seconding the second task regarding image placement. I want to pan down to a jungle canopy, so I'd like that image to be centered and span the entire available space. A setting or configuration option for that would be much preferred over tinkering with the `img` style.

**Comment by wrycu** [comment]
I'm delaying short intos for another time.  The other things in the list (including image placement) are done.  This will be released in `0.1.10`.
