### ISSUE TITLE
Explore shop generator

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#26]
Similar to https://www.swrpg-shop.com/. Perhaps from in-game items.

The current workflow to get a shop up is to create a new actor and change their sheet to the "vendor" type. I have added a scene button to create it as well, but it isn't functional right now (it'll error out and quit).

**Comment by wrycu** [comment]
todo:

- [ ] Add localization support
- [ ] Support specific item types (e.g. exclude shipweapons from the "weapon" store)
- [ ] Merge in the changes from @Rysarian, which permit using local items
- [ ] Make things configurable, e.g. compendium names, local item support
- [ ] Investigate better shop output options

For better shop output options, I'm thinking about a scene such as this:
![image](https://user-images.githubusercontent.com/4709746/116292386-7eb2d600-a74a-11eb-9a9f-1a3f73a6bd4b.png)
Alternatively, it's been suggested to implement something like a [vendor sheet](https://github.com/jopeek/fvtt-loot-sheet-npc-5e)

**Comment by Sonny-Crockett** [comment]
- I think having a global discount or upcharge that could be affected by (%) would be useful. 

- The ability to manually add items from the compendium to an already generated list would be great to make sure a certain item was there on a "fixed" list provided for players. If an NPC sheet would be used in addition to the table this is a moot point as one could do this already by dragging items. 

General Shopping Discussion: [Reddit Link](https://www.reddit.com/r/swrpg/comments/8d8598/gm_help_how_does_shopping_work/)

**Comment by wrycu** [comment]
@Sonny-Crockett drag and drop items are now supported. In theory this will work, though in practice I've only tested it with drag-and-dropped items from the local world.

**Comment by wrycu** [comment]
I'm considering hiding the roll result from the players. The GM can do something with it if they want, but I don't think there's any value in the PCs seeing it.

**Comment by wrycu** [comment]
The above-commit requires regenerating shop inventory or it'll break.

**Comment by wrycu** [comment]
This is now reasonably complete. I'm gonna start using it and looking for ways to improve it / bugs which need fixing.

**Comment by wrycu** [comment]
Need to fix the restricted tag for auto-added items.
