### ISSUE TITLE
[Bug] Can't attack with compedium weapons

### ISSUE THREAD

**Issue by Havoclivekiller** [wrycu/StarWarsFFG-Enhancements#28]
I've had a character (let's say an adversary) that already had a lightsaber. Then I've imported (from the compendium) a new weapon (non-lightsaber) and couldn't make rolls and an exception started to show up in the console.

![image](https://user-images.githubusercontent.com/21118924/118762551-acd19480-b876-11eb-9555-b9d20cc45622.png)

`2dice-helpers.js:64 Uncaught (in promise) TypeError: Cannot read property 'uuid' of null
    at Function.rollSkill (dice-helpers.js:64)
    at async HTMLDivElement.<anonymous> (actor-sheet-ffg.js:491)`

**Comment by Havoclivekiller** [comment]
Maybe the fault is that its a token sheet, as it works with the actor sheet.

**Comment by wrycu** [comment]
Looking at the stack trace, it appears to be a base system error. Are you sure the module is causing it?

**Comment by Havoclivekiller** [comment]
You are correct. It's a system bug.
