### ISSUE TITLE
[Compatibility] Star Wars UI

### ISSUE THREAD

**Issue by Havoclivekiller** [wrycu/StarWarsFFG-Enhancements#32]
https://github.com/prolice/swffgUI-cc

There are issues with compatibility with the Star Wars UI. I don't know if I should have the issue raised here or there.

![image](https://user-images.githubusercontent.com/21118924/118765708-bf9a9800-b87b-11eb-849c-e115efe1c0bf.png)

**Comment by wrycu** [comment]
I'll keep taking a look, but I'd suggest opening a ticket with the other module. The bounty classes are not present with both modules loaded but are present without the SW UI loaded, which leads me to believe it's clobbering stuff we're setting.

**Comment by Havoclivekiller** [comment]
I've raised the issue on the SW UI github.

**Comment by wrycu** [comment]
Closing for now. If they claim it's our problem, feel free to re-open and I'll check more.
