### ISSUE TITLE
[Bug] Large Image/Resolution Crawl

### ISSUE THREAD

**Issue by Havoclivekiller** [wrycu/StarWarsFFG-Enhancements#33]
Best would be to have some dimension restrictions or resize the image. Also, the crawl feels very small in high resolution (a long time ago is okay, the logo too). Barely 1/3 of the screen.
![image](https://user-images.githubusercontent.com/21118924/118931254-102af780-b947-11eb-82e5-2ee3195646bf.png)

![image](https://user-images.githubusercontent.com/21118924/118931527-6dbf4400-b947-11eb-9d34-d3d83704f438.png)

**Comment by wrycu** [comment]
Thanks. I've folded this into #24.
