### ISSUE TITLE
Attack Animations and Combat Result Spending Tips don't work with Spanish translation

### ISSUE THREAD

**Issue by llednar91** [wrycu/StarWarsFFG-Enhancements#34]
I have tried with Spanish and French translations, but it seems that only the English option works.

**Comment by wrycu** [comment]
Sorry about that; there were hard-coded references to the English translation. I've removed them. 

Fixed, will be released in `0.1.8`.  You can try it for yourself by installing from the `dev` branch, if you feel so inclined.
