### ISSUE TITLE
Attack Animation – custom animation not shown

### ISSUE THREAD

**Issue by ProjectAvalanchi** [wrycu/StarWarsFFG-Enhancements#38]
I placed a link to a not standard JB2A file, but the animation is not shown on attack roll

**Comment by wrycu** [comment]
Can you include the resource in the issue or DM it to me on Discord?  I'm inclined to say that this is a result of choosing an animation file type that `fxmaster` (which actually plays the file) doesn't support, but I can't be sure without being able to reproduce the issue.

**Comment by ProjectAvalanchi** [comment]
My mistake, the „select“ button leads to the “picture browser”. So everyone get offered only pictures instead animations – and I didn’t recognised it till now.

**Comment by ProjectAvalanchi** [comment]
Not using the select botton an placing the link direktly, the animation works.

**Comment by ProjectAvalanchi** [comment]
Thanks for the fantastic work

**Comment by wrycu** [comment]
No worries, thanks for creating an issue. I've created #41 to try and improve the flow.
