### ISSUE TITLE
Optional Initiative Renaming

### ISSUE THREAD

**Issue by basicgm** [wrycu/StarWarsFFG-Enhancements#44]
Consider making the `Initiative Slot Renaming` feature *optional* via a setting in the module configuration.

Not all tables use the renaming system, but it should perhaps default to being `enabled` as this is the default for the system as written.

Initial request here: https://discord.com/channels/170995199584108546/718281676333252660/847947817448505344

**Comment by wrycu** [comment]
Unless I'm misunderstanding something, this is already a thing.
![image](https://user-images.githubusercontent.com/4709746/120046777-c33ec500-bfc7-11eb-9734-4fc3059b0730.png)
