### ISSUE TITLE
Request for Reset/Clear button in the Attack Animation pop window

### ISSUE THREAD

**Issue by iriutta** [wrycu/StarWarsFFG-Enhancements#45]
If I have entered a bunch of stuff and I just want to go back to default, it would be great to have a button to just reset this character's weapon.
![image](https://user-images.githubusercontent.com/81662150/120128783-d51f9400-c190-11eb-8d31-24c64000e4fc.png)

**Comment by wrycu** [comment]
Done; will be released in `0.1.11`. Thanks for the suggestion!
