### ISSUE TITLE
Request for Explosive category for Attack Animations

### ISSUE THREAD

**Issue by iriutta** [wrycu/StarWarsFFG-Enhancements#46]
It might be cool to add another category in the default settings for ranged light explosives. It would search for things with blast and limited ammo weapon qualities and apply the animation and audio when playing those ranged light weapons. Almost all explosives have those two qualities. (minus glop grenades and a handful of others).

**Comment by wrycu** [comment]
If you can find a reasonable (and open-source) animation for it, I'll include it.  Otherwise, I think this is covered by permitting users to set it on a per-item basis.

**Comment by iriutta** [comment]
I requested a grenade toss one in the JB2A site. In the meantime perhaps you can use the Magic Missile one with an Explosion Orange at the end from here? 
https://www.jb2a.com/Library_Preview/
modules/JB2A_DnD5e/Library/1st_Level/Magic_Missile/MagicMissile_01_Regular_Purple_30ft_01_1600x400.webm
modules/JB2A_DnD5e/Library/Generic/Explosion/Explosion_01_Orange_400x400.webm

**Comment by wrycu** [comment]
I've added it for items with the word "grenade" in their name. Thanks for the suggestion!

Will be released in `0.2.1`.
