### ISSUE TITLE
Request delay option for the animation/audio file in the Attack animations

### ISSUE THREAD

**Issue by iriutta** [wrycu/StarWarsFFG-Enhancements#47]
Would be nice to add a delay to the audio/animation file for the attack animations. The flame jet for instance has an animation that sucks air in before shooting out flame and it would be rad to put a delay on the audio.

**Comment by wrycu** [comment]
I am strongly inclined to believe that it's easier to fix the files than it is to add one or two more options for every attack animation - there are already a lot and it can be overwhelming.

That being said, I may add it as part of the per-item override.

**Comment by wrycu** [comment]
I don't think this is worth the effort or added complexity for the UX. Closing.
