### ISSUE TITLE
Dice roll from Combat Skills via Token Action HUD broken when targeting token.

### ISSUE THREAD

**Issue by ReytroPanda** [wrycu/StarWarsFFG-Enhancements#48]
When a token is targeting another token, clicking a Combat Skill via Token Action HUD (T.A.HUD) brings up the dice pool window, but clicking roll does nothing (except make the dice pool window disappear like when dice have been rolled).

Issue does not occur if token is not targeted, but this means animations will not played.

While not an issue for main characters, T.A.HUD only updates dice pools for minion group size in the Combat Skills section,  Weapon dice pools are based on original actor sheet and do not update, meaning minion groups rely on dice pools from Combat Skills as opposed to Weapons via T.A.HUD

Unable to capture issue in screenshot,  pic attached shows situation set up before roll button is clicked and issue occurs.

![Screenshot 2021-06-05 at 17 20 36](https://user-images.githubusercontent.com/85407835/120898937-1a2a4700-c625-11eb-9558-a7233ee23ea8.png)
.

**Comment by wrycu** [comment]
Works for me. What version of the system and Foundry are you running?

**Comment by ReytroPanda** [comment]
Occurs for me on Foundry 0.7.10, Star Wars FFG 1.5, FFG Enhancements 0.1.10, Token Action HUD 1.0.22.

**Comment by ReytroPanda** [comment]
Just learned you can upload vids to here.

Apologies for it being quick, but uploads are limited to 10mb.  In vid I show Pash targeting an enemy, trying to roll from combat skills did not work for ranged light, ranged heavy, but then untargeting it works fine.


https://user-images.githubusercontent.com/85407835/120937533-e70bb480-c705-11eb-8c85-649fe9dc4ba9.mov

**Comment by wrycu** [comment]
Got it. I haven't tested for compatibility with `1.5` yet, but I did test for Foundry `0.7.10` (and it works). I'll look into what's causing the failure on `1.5` in the near future; thanks for the report.

**Comment by wrycu** [comment]
Fixed; will be released in `0.1.11`. Thanks again for the report and video :)
