### ISSUE TITLE
Allow players to use result spender

### ISSUE THREAD

**Issue by Aethen22** [wrycu/StarWarsFFG-Enhancements#51]
Right now they cant do it because the message is sent as "Gamemaster" and they cant update a GM message(Lack of permissions, which is a good thing most of the times because we dont want players able to mess with GM messages), or at least that's what im guessing it may be.
Said button(Player who said it was Gamemaster):
![image](https://user-images.githubusercontent.com/70035010/123554982-25cfe000-d783-11eb-985c-b58d3a7c82a1.png)
Said error(Lacks permission, my guess is the above reason):
![image](https://user-images.githubusercontent.com/70035010/123555042-89f2a400-d783-11eb-8e65-5b3da6c66705.png)

**Comment by Aethen22** [comment]
A friend of mine(and player in my campaign) fixed it this way.
Sustituted line 38 of dice_helper.js to this:
            if (messageData.message.user === game.userId && app.roll && (messageData.message.content.search('Initiative') === -1 || messageData.message.content.search('Help spending results') === -1 || messageData.message.content.search('for spending results') === -1)) {

**Comment by wrycu** [comment]
Done, will be released in `0.2.0`.
