### ISSUE TITLE
feature request. Alternatieve optional change for changing token strain and wounds

### ISSUE THREAD

**Issue by BlackburnUTG** [wrycu/StarWarsFFG-Enhancements#55]
I would like to have the ability to add wounds/strain with "-" and heal with "+". Right now it is the opposite
can it be a optional thing, what do you think?

**Comment by wrycu** [comment]
I suspect modules already exist to do this for tokens (not just for star wars). Closing as won't do, but consider opening the request against the core system instead. Maybe they'll add a toggle.
