### ISSUE TITLE
Clicking Star Wars FFG Enhancements button does nothing...

### ISSUE THREAD

**Issue by EctoNoodle** [wrycu/StarWarsFFG-Enhancements#57]
I'm in a scene, but the button isn't doing anything.
I've tried the wiki and google but that doesn't give me any answers.
Been going over the module settings and yet again, no answers...

Please help.

**Comment by wrycu** [comment]
What version of Foundry, Star Wars, and the module are you using?

**Comment by EctoNoodle** [comment]
Foundry 0.8.8
Star Wars ffg 1.6
Enhancement 01.11

**Comment by wrycu** [comment]
Foundry `0.8.x` is not supported yet, see #52. The next release will work on it - I plan to release it today or tomorrow.
