### ISSUE TITLE
Intro Crawl music and logo

### ISSUE THREAD

**Issue by EctoNoodle** [wrycu/StarWarsFFG-Enhancements#58]
Sorry to come here once again with questions, but for an unexperienced player there is a disturbing lack of information available and many things are incredibily unclear...

The enhancement button is working and I'm trying to make a custom crawl for my session next sunday.
I have waited as long as I can before coming here but I just can't get it to work.

When trying to add music it doesn't select it. I can search and choose but when I click select file nothing happens and the file is not added. The opening crawl music box is left blank, same goes for a custom logo, I can search it, choose it and when I press select file nothing happens.

Is it a special kind of file extension that I need (i've tried several already with no success) or is it another compatibility issue?

**Comment by Tenebros** [comment]
Get the link of your music and copy / paste, I have the same

**Comment by EctoNoodle** [comment]
Thank you, got it to somewhat work, just need to adjust delay etc, is there anyway to stop the music when you close the crawl window? Also it's super loud and I don't see any volume controls...

**Comment by wrycu** [comment]
The music player uses the global volume as the control. Adjust that and the intro crawl volume will change.
