### ISSUE TITLE
Include existing macros

### ISSUE THREAD

**Issue by bheiskell** [wrycu/StarWarsFFG-Enhancements#6]

**Comment by wrycu** [comment]
- [ ] Obligation macro
- [ ] Random cantina NPC macro

**Comment by bheiskell** [comment]
Here are my copies of the macros:

- https://pastebin.com/9VLZKd9p
- https://pastebin.com/hwnPmtcp
- https://pastebin.com/jjiyrLFu
- https://pastebin.com/pyqtnWxE
- https://pastebin.com/pszYNuTT

**Comment by bheiskell** [comment]
- [ ] Obligation
- [ ] Random cantina NPC
- [ ] Critical - https://pastebin.com/9VLZKd9p
- [ ] Boost/Setback to Actor - https://pastebin.com/hwnPmtcp
- [ ] Boost to next combat slot - https://pastebin.com/jjiyrLFu
- [ ] Configure Encounter - https://pastebin.com/pyqtnWxE
- [ ] Configure Tokens with Consistent Displays - https://pastebin.com/pszYNuTT

**Comment by wrycu** [comment]
Perhaps also https://github.com/StarWarsFoundryVTT/StarWarsFFG/wiki/helpful-macros#set-the-token-default-status-bars

**Comment by wrycu** [comment]
![image](https://user-images.githubusercontent.com/4709746/113493961-033a6d80-9499-11eb-9e4e-169208375504.png)
done
