### ISSUE TITLE
Suggestion to add Triumph/Despair results

### ISSUE THREAD

**Issue by Theik** [wrycu/StarWarsFFG-Enhancements#66]
If you look at all the tables in the book, the result is pretty much always "1 advantage OR 1 triumph", but currently the system does not list the options for advantage choices if you roll a triumph.

One way to fix that is to duplicate all the entries in the json but that will result in a huge mess of duplicate entries, so I instead hacked the code a bit. 

This is just an example, you'll likely want to make it a module option you can turn on or off, but this is my approach:

Replace the array building system around line 190 with:

`// build an array of the suggestions for the specific category we're looking at now
        let tmp_suggestions = [];
        if((category === 'ad' && results['tr'] > 0) || (category === 'th' && results['de'] > 0) ) {
            tmp_suggestions = data[skill][category];
        } else {
            tmp_suggestions = data[skill][category].filter(suggestion => suggestion.required <= results[category]);
        }`

This will make it that if you roll a triumph, all advantage suggestions will go through, if you roll a despair, all threat suggestions will go through.

![image](https://user-images.githubusercontent.com/6170572/131245997-0609ce61-e239-4298-b220-a97b90e1cc47.png)

**Comment by wrycu** [comment]
Good idea, I've implemented it. Thanks for the code suggestion, too!

Will be released in `0.2.1`.
