### ISSUE TITLE
Further Improve Shop

### ISSUE THREAD

**Issue by wrycu** [wrycu/StarWarsFFG-Enhancements#67]
Some additional nice things to have:

- [ ] The ability to set the character image (there's a workaround for this but it should be supported)
- [ ] Versioned metadata to allow it to continue to grow over time
- [ ] Configuration for keeping items when regenerating the inventory
- [ ] Configuration for manually pricing items
- [x] Update base price of not 100% to show int prices
- [ ] ??

**Comment by HaxxonHax** [comment]
Can we make the price modifier a bit more apparent (e.g., "Uncivilized World (x4)").  As it stands, it feels obfuscated.

**Comment by wrycu** [comment]
Sadly, no. The intent is to supplement the books, not replace them. As such, it's up to you to be familiar with what the various choices mean.
