### ISSUE TITLE
Relative URLs don't resolve on servers using a routePrefix

### ISSUE THREAD

**Issue by anthonyscorrea** [wrycu/StarWarsFFG-Enhancements#68]
The css file doesn't take into account a server with a routePrefix.

They're in the form

`url("/modules/ffg-star-wars-enhancements/fonts/NewsCycle-Regular.ttf")`

This relative link does not work for campaigns that have an address like "https://myrpgdomain.com/foundry/" who's style file would be at "https://myrpgdomain.com/foundry/modules/ffg-star-wars-enhancements/fonts/NewsCycle-Regular.ttf" the relative path above always resolves to "https://myrpgdomain.com/modules/ffg-star-wars-enhancements/fonts/NewsCycle-Regular.ttf" which will not work.

**Comment by anthonyscorrea** [comment]
should be:
`url("../fonts/NewsCycle-Regular.ttf")`

instead of 
`url("/modules/ffg-star-wars-enhancements/fonts/NewsCycle-Regular.ttf")`

**Comment by wrycu** [comment]
Thanks for the report and the fix.

Fixed; will be released in `0.2.2`.
