### ISSUE TITLE
Flush out a contributors.md

### ISSUE THREAD

**Issue by bheiskell** [wrycu/StarWarsFFG-Enhancements#7]
This should include information around not uploading copy written assets.

**Comment by wrycu** [comment]
It should also include the overall philosophy of the module design, e.g. each feature we provide should be individually togglable such that people can turn it on/off as desired.

**Comment by wrycu** [comment]
Additionally, things should be implemented via feature branches from `dev` and then merged into `dev` once completed (for now).
