### ISSUE TITLE
Intro crawl ends before the end of the text

### ISSUE THREAD

**Issue by Orden-3723** [wrycu/StarWarsFFG-Enhancements#71]
intro crawl is fading away before the end of the text.

as it is based upon kassellabs intro generator code it should work as theirs, but there is a discrepancy coming from somewhere and I wasn't able to find it.

**Comment by Orden-3723** [comment]
@bheiskell I found this in kassellabs js source code, and I though this may be the missing par of your adaptation but manualy changing the value in the css file doesn't seemed to have an impact on the animation on my client.
```md
const DEFAULT_LENGTH = 1977;
    const ANIMATION_CONSTANT = 0.04041570438799076;
    const FINAL_POSITION = 20;

    this.animationContainer.appendChild(this.animation);

    // adjust animation speed
    const titlesContainer = this.animation.querySelector('#titles > div');
    if (titlesContainer.offsetHeight > DEFAULT_LENGTH) {
      const exceedSize = titlesContainer.offsetHeight - DEFAULT_LENGTH;
      const animationFinalPosition = FINAL_POSITION - (exceedSize * ANIMATION_CONSTANT);
      appendKeyframesRule('titlesAnimation', `100% { top: ${animationFinalPosition}% }`);
```

**Comment by bheiskell** [comment]
Hey folks, I'm trying to replicate this problem locally, but in my environment (Firefox/Chrome) it seems to function as expected. Are you folks operating with an unusual resolution or long opening crawls?

I will 100% admit that I don't fully understand all the CSS magic involved to make this happen. I also don't know if you can modify CSS animations via JavaScript to make this dynamically configurable. But if I can reproduce this, I'm happy to look into this.

**Comment by bheiskell** [comment]
I got a fix up for the issue. It was an omission from when I did the original port. I missed an override of the keyframes shifting the top up by -20% during the fade out.  The code as it was stopped the animation 20% short of the top. This will still be a problem for really long crawls, but it will at least handle the Teemo crawl correctly. To fix this more robustly, I think we could correct it by dynamically controlling the height of the object containing the text. Specifically the height assigned to `.ffg-star-wars-enhancements-opening-crawl .titles` of `50em` currently. I don't know how to dynamically detect size of an element, so for now, I'd like to see if this addresses folk's issues. If not, please re-open.

**Comment by bheiskell** [comment]
Okay, I actually attempted the second part of what I suggested above and it does work, but it's not useful. With longer texts, the opening crawl scrolls by so fast you have to be able to speed read. If we decide we still want that in the future, this is the code I changed:

```
diff --git a/scripts/opening_crawl.js b/scripts/opening_crawl.js
index b998e34..9d0af1b 100644
--- a/scripts/opening_crawl.js
+++ b/scripts/opening_crawl.js
@@ -156,6 +156,12 @@ class OpeningCrawlApplication extends Application {
         log('opening-crawl', 'active listeners');
         super.activateListeners(html);

+        let height = $(".ffg-star-wars-enhancements-opening-crawl .text")[0].offsetHeight;
+        if (height < 2800) { // Approximately what the current 50em height translates to
+            height = 2800;
+        }
+        $(".ffg-star-wars-enhancements-opening-crawl .titles")[0].style.height = height + "px";
+
         // When music is configured, hide the HTML until the audio loaded is
````
