### ISSUE TITLE
Unable to roll certain weapons when module is enabled.

### ISSUE THREAD

**Issue by GhstDragon** [wrycu/StarWarsFFG-Enhancements#72]
I just used the Module and it's great for using opening crawls and animations but for certain weapons such as grenades or disruptor rifles the dice won't even roll. Is there something I have to enable or do to make it work correctly? It's a bummer because I love the module but I'm not going to enable it if it won't roll all the weapons.

**Comment by GhstDragon** [comment]
Foundry Core Version 0.8.9, Module versions 0.2.1, Star Wars FFG, Frag
grenade with light ranged stat listed roll on character sheet from
inventory list targeting specific enemy and click roll, dice and roll show
in chat log. When I am not targeting an enemy the roll happens but says I
must target an enemy to initiate the attack animation.

**Comment by GhstDragon** [comment]
Sorry EDIT: Foundry Core Version 0.8.9, Module versions 0.2.1, Star Wars
FFG, Frag grenade with light ranged stat listed roll on character sheet
from inventory list targeting specific enemy and click roll, dice and roll
do NOT show in chat log. When I am not targeting an enemy the roll happens
but says I must target an enemy to initiate the attack animation.

**Comment by wrycu** [comment]
Fixed, will be released in `0.2.2`.
