### ISSUE TITLE
Make Module System Agnostic

### ISSUE THREAD

**Issue by RedneckRPGer** [wrycu/StarWarsFFG-Enhancements#75]
Is there any way, or possibility, of making the Module system agnostic.  There's some really nice features here that could transfer well to - for example - the Alien RPG System, or the UnofficialAGE System.

**Comment by wrycu** [comment]
Most of it is tied pretty closely to the star wars system. I'd be willing to entertain helping convert some of the code to be system agnostic (where possible), but it isn't practical to convert the entire module.
