### ISSUE TITLE
'Bug' in the dice_helper if the skill name contains a & sign

### ISSUE THREAD

**Issue by Theik** [wrycu/StarWarsFFG-Enhancements#80]
This is a problem that is likely never going to show up again for anybody, but I'm using the plugin to run it with my Genesys homebrew skillset, and one of the skills has an & sign in it. When the json template is saved, it'll parse this & into an &amp;, which later causes the dice roll helper to fail, as it will try to read a & when it should be reading an &amp;.

It's an extremely minor problem which is unlikely to ever happen again for anybody else, but if you want to enable functionality for & symbols, you can alter line 181 of dice_helper.js by turning it into:

`let skill = results['skill'].toLowerCase().replace('&', '&amp;');`

The replace there will make it able to find the html entities converted entry, at which point it'll start working again.

**Comment by wrycu** [comment]
Fixed in the above commit. Will be released in `0.2.3`. Thanks for the report!
