### ISSUE TITLE
Attack Animation Settings Cuts Off Window At Lower Resolutions

### ISSUE THREAD

**Issue by OutlandishVillainy** [wrycu/StarWarsFFG-Enhancements#91]
At lower resolutions (such as 1440x900 like mine), the lower part of the attack animation settings window can't be seen or scrolled down to, making it impossible to get to the save button at the bottom.

![unknown](https://user-images.githubusercontent.com/93902659/149755154-d399d2a7-6a16-43f7-b3e3-7016577eae96.png)

**Comment by bheiskell** [comment]
I took a crack at fixing this. @wrycu what do you think of this?
![image](https://user-images.githubusercontent.com/96167/149803739-faa722cb-dc26-443f-ac3c-3f888afe6af8.png)

**Comment by bheiskell** [comment]
Chose a different path with @wrycu 
![image](https://user-images.githubusercontent.com/96167/149820922-61762a56-fce2-4e01-9f12-58d99b3f6208.png)
