### ISSUE TITLE
Certain Imported Scenes Cause Immense Foundry Slow Down

### ISSUE THREAD

**Issue by OutlandishVillainy** [wrycu/StarWarsFFG-Enhancements#92]
Certain imported scenes, galaxy map, space combat, and ship (space), when viewed cause immense slow down to the point it seems like Foundry has frozen. If left long enough, the scene will turn white, but this doesn't affect Foundry being "frozen". This is the console error I get when it happens.

![Untitled](https://user-images.githubusercontent.com/93902659/149756200-ab26d466-f71c-4d89-a14e-13c206736ce7.png)

**Comment by bheiskell** [comment]
I’m pretty sure the white is because of the scene effects. I think they changed the calculation causing the stars on the scene to render huge. I’ll take a look at fixing that. It’s likely why they’re also performing badly.

**Comment by bheiskell** [comment]
Strong correlation here:
```
ffg-star-wars-enhancements/packs$ grep fxmaster * | sed 's/\(.\{80\}\).*/\1/'
sceneideas.db:{"name":"Ship (Hyperspace)","permission":{"default":0,"vchzNx2bcUl
sceneideas.db:{"name":"Ship (Space)","permission":{"default":0,"vchzNx2bcUllLpJW
sceneideas.db:{"name":"Space Combat","permission":{"default":0,"vchzNx2bcUllLpJW
sceneideas.db:{"name":"Galaxy Map","permission":{"default":0,"vchzNx2bcUllLpJW":
```

**Comment by bheiskell** [comment]
Replicated the bug and confirmed disabling fxmaster address the issue. I'm going to try to fix this manually in the scenes.
