### ISSUE TITLE
Star Wars FFG Enhancments Mod, Vehicle Roller option

### ISSUE THREAD

**Issue by ProfessorKiz** [wrycu/StarWarsFFG-Enhancements#96]
The window will open up, how ever it is not click able. Only work around for now is to disable this option in the mod
![SWFFG_Enhancments_Vehicle Roller](https://user-images.githubusercontent.com/97915523/149830613-936ac031-4bf3-4bec-9740-82dcaba940bd.png)
.

**Comment by wrycu** [comment]
Fixed, pending release in `0.2.6`.

Thanks for the report!
