### ISSUE TITLE
Rolling for Gunnery using a Crewmember fail to bring roll dice dialog

### ISSUE THREAD

**Issue by Szyna1988** [wrycu/StarWarsFFG-Enhancements#97]
Everything was done as the wiki says, after clicking to test Gunnery using Vehicle sheet, a popup windows occurs where I can choose a crewmember to make a test. When clicking to make a test, nothing happens and following error occurs in console:

![image](https://user-images.githubusercontent.com/64432102/150833221-b6ff3a2b-bd2e-4329-92e3-656cf8e76dee.png)

**Comment by wrycu** [comment]
Please include the version of Foundry, system, and module you're using.

**Comment by Szyna1988** [comment]
Foundry v 0.9     with system ver 1.71, module 0.2.5. Failed to notice there is a 0.2.7 version. Updated to 0.2.7. 

When leaving animations disabled, everything works fine, dice roller pops up, I can make roll and everything is calculated properly. 

When activating animations, clicking roll button closes dice roller, and nothing is sent to chat and no animation is being played. The error persists even with all the modules turned off except of enhancements of course (and its dependendies) This is the error in console:

![image](https://user-images.githubusercontent.com/64432102/150935708-225f90a2-c5f6-4845-a782-67038ce8bf77.png)

**Comment by wrycu** [comment]
Thanks.  I looked into it a bit and confirmed that this only happens on Foundry v9 with both the crew and animations enabled. Very odd; will continue looking into it.

**Comment by wrycu** [comment]
Fixed; will be released in `0.2.8`.
