### ISSUE TITLE
[Bug] Module shows up in list for non-SWFFG systems

### ISSUE THREAD

**Issue by esheyw** [wrycu/StarWarsFFG-Enhancements#99]
https://i.imgur.com/SBTY8ti.png this is in a pf2e world.

Looking at your module.json, I see you have the system as a dependency, but no top level `"system":["starwarsffg"]`, which I think is the problem.

**Comment by wrycu** [comment]
Ha. I'll test this out at some point. I only use Foundry for SW FFG :)

**Comment by wrycu** [comment]
Fixed; will be released in `0.2.8`. Thanks for the report, and even more thanks for the fix!
